{
 "title": "Indoor",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "indoor_state{topic=\"indoor_sensor_roof_temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "indoor_state{topic=\"indoor_sensor_roof_humidity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "indoor_state{topic=\"indoor_sensor_roof_brightness\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}