esphome:
  name: indoor
  friendly_name: Indoor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

ota:
  - platform: esphome
    password: "21232f297a57a5a743894a0e4a801fc3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.0.14
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Casa Fallback Hotspot"
    password: "8LW7uXRvPPj4"

captive_portal:

mqtt:
  topic_prefix: indoor
  discovery: false
  broker: "192.168.0.19"
  port: 1883
  clean_session: true
  birth_message:
    topic: esp/devices
    payload: 'Booting ESP32'
  will_message:
    topic: esp/devices
    payload: 'Shutdown ESP32'
  on_message: []

# Example configuration entry
sensor:
  - platform: dht
    pin: GPIO4

    temperature:
      name: "Roof Temperature"
      qos: 1
      retain: false
      expire_after: 60s
    humidity:
      name: "Roof Humidity"
      qos: 1
      retain: false
      expire_after: 60s
    update_interval: 60s

  - platform: adc
    pin: GPIO34
    name: "Roof Brightness"
    update_interval: 60s
    qos: 1
    retain: false
    expire_after: 60s
    filters:
    - lambda: return x * (-100) + 100;
    - median:
        window_size: 5
        send_every: 4
        send_first_at: 3

